"""Simplify Ad model

Revision ID: 1f9de643d3db
Revises: aa46db9d1fef
Create Date: 2026-02-13 18:47:01.445957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9de643d3db'
down_revision = 'aa46db9d1fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('link_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_column('clicks')
        batch_op.drop_column('impressions')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index('idx_airport', ['airport_icao'], unique=False)
        batch_op.create_index('idx_created', ['created_at'], unique=False)
        batch_op.create_index('idx_price', ['price_month'], unique=False)
        batch_op.create_index('idx_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_price')
        batch_op.drop_index('idx_created')
        batch_op.drop_index('idx_airport')

    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impressions', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('clicks', sa.INTEGER(), nullable=True))
        batch_op.alter_column('link_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
