"""Add performance indexes and caching

Revision ID: 0ffc0fbe7553
Revises: 1f9de643d3db
Create Date: 2026-02-14 22:38:37.258298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffc0fbe7553'
down_revision = '1f9de643d3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index('idx_covered', ['covered'], unique=False)
        batch_op.create_index('idx_featured', ['is_featured'], unique=False)
        batch_op.create_index('idx_owner', ['owner_id'], unique=False)
        batch_op.create_index('idx_premium_listing', ['is_premium_listing'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('idx_premium_listing')
        batch_op.drop_index('idx_owner')
        batch_op.drop_index('idx_featured')
        batch_op.drop_index('idx_covered')

    # ### end Alembic commands ###
