"""Initial schema

Revision ID: 29b28564bde5
Revises: 
Create Date: 2026-02-19 18:44:40.465338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b28564bde5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=False),
    sa.Column('placement', sa.String(length=50), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('alert_enabled', sa.Boolean(), nullable=True),
    sa.Column('alert_airport', sa.String(length=4), nullable=True),
    sa.Column('alert_max_price', sa.Float(), nullable=True),
    sa.Column('alert_min_size', sa.Integer(), nullable=True),
    sa.Column('alert_covered_only', sa.Boolean(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('rentals_count', sa.Integer(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_expires', sa.DateTime(), nullable=True),
    sa.Column('has_analytics_access', sa.Boolean(), nullable=True),
    sa.Column('analytics_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('search_count_today', sa.Integer(), nullable=True),
    sa.Column('search_reset_date', sa.Date(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('is_certified', sa.Boolean(), nullable=True),
    sa.Column('seasonal_alerts', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('username')
    )
    op.create_table('white_label_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fbo_name', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airport_icao', sa.String(length=4), nullable=False),
    sa.Column('size_sqft', sa.Integer(), nullable=False),
    sa.Column('covered', sa.Boolean(), nullable=True),
    sa.Column('price_month', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photos', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('featured_expires_at', sa.DateTime(), nullable=True),
    sa.Column('featured_tier', sa.String(length=20), nullable=True),
    sa.Column('insurance_active', sa.Boolean(), nullable=True),
    sa.Column('condition_verified', sa.Boolean(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('virtual_tour_url', sa.String(length=255), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('checklist_completed', sa.Boolean(), nullable=True),
    sa.Column('availability_start', sa.Date(), nullable=True),
    sa.Column('availability_end', sa.Date(), nullable=True),
    sa.Column('is_premium_listing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index('idx_airport', ['airport_icao'], unique=False)
        batch_op.create_index('idx_covered', ['covered'], unique=False)
        batch_op.create_index('idx_created', ['created_at'], unique=False)
        batch_op.create_index('idx_featured', ['is_featured'], unique=False)
        batch_op.create_index('idx_listing_airport', ['airport_icao'], unique=False)
        batch_op.create_index('idx_listing_created', ['created_at'], unique=False)
        batch_op.create_index('idx_listing_price', ['price_month'], unique=False)
        batch_op.create_index('idx_listing_status', ['status'], unique=False)
        batch_op.create_index('idx_owner', ['owner_id'], unique=False)
        batch_op.create_index('idx_premium_listing', ['is_premium_listing'], unique=False)
        batch_op.create_index('idx_price', ['price_month'], unique=False)
        batch_op.create_index('idx_status', ['status'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('renter_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stripe_payment_id', sa.String(length=100), nullable=True),
    sa.Column('insurance_opt_in', sa.Boolean(), nullable=True),
    sa.Column('insurance_fee', sa.Float(), nullable=True),
    sa.Column('owner_rating', sa.Integer(), nullable=True),
    sa.Column('renter_rating', sa.Integer(), nullable=True),
    sa.Column('owner_review', sa.Text(), nullable=True),
    sa.Column('renter_review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['renter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=True),
    sa.Column('guest_email', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('bookings')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_price')
        batch_op.drop_index('idx_premium_listing')
        batch_op.drop_index('idx_owner')
        batch_op.drop_index('idx_listing_status')
        batch_op.drop_index('idx_listing_price')
        batch_op.drop_index('idx_listing_created')
        batch_op.drop_index('idx_listing_airport')
        batch_op.drop_index('idx_featured')
        batch_op.drop_index('idx_created')
        batch_op.drop_index('idx_covered')
        batch_op.drop_index('idx_airport')

    op.drop_table('listings')
    op.drop_table('white_label_request')
    op.drop_table('users')
    op.drop_table('ad')
    # ### end Alembic commands ###
