"""Add smart handover fields to Listing

Revision ID: 5ea44fc66030
Revises: 879ed77e6f60
Create Date: 2026-04-01 21:45:55.588378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea44fc66030'
down_revision = '879ed77e6f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_location_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('private_access_instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('private_access_instructions')
        batch_op.drop_column('public_location_description')

    # ### end Alembic commands ###
