"""Scale optimizations

Revision ID: 879ed77e6f60
Revises: 29b28564bde5
Create Date: 2026-02-24 21:30:02.748898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879ed77e6f60'
down_revision = '29b28564bde5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_airport'))
        batch_op.drop_index(batch_op.f('idx_covered'))
        batch_op.drop_index(batch_op.f('idx_created'))
        batch_op.drop_index(batch_op.f('idx_featured'))
        batch_op.drop_index(batch_op.f('idx_owner'))
        batch_op.drop_index(batch_op.f('idx_premium_listing'))
        batch_op.drop_index(batch_op.f('idx_price'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.create_index('idx_listing_covered', ['covered'], unique=False)
        batch_op.create_index('idx_listing_featured', ['is_featured'], unique=False)
        batch_op.create_index('idx_listing_owner', ['owner_id'], unique=False)
        batch_op.create_index('idx_listing_premium', ['is_premium_listing'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('idx_listing_premium')
        batch_op.drop_index('idx_listing_owner')
        batch_op.drop_index('idx_listing_featured')
        batch_op.drop_index('idx_listing_covered')
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_price'), ['price_month'], unique=False)
        batch_op.create_index(batch_op.f('idx_premium_listing'), ['is_premium_listing'], unique=False)
        batch_op.create_index(batch_op.f('idx_owner'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('idx_created'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_covered'), ['covered'], unique=False)
        batch_op.create_index(batch_op.f('idx_airport'), ['airport_icao'], unique=False)

    # ### end Alembic commands ###
