"""make price_month nullable

Revision ID: b9ab572e5e51
Revises: 5ea44fc66030
Create Date: 2026-04-02 14:18:52.740774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ab572e5e51'
down_revision = '5ea44fc66030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('price_month',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('price_month',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
